{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: {{ include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}
spec:
  endpoints:
    - targetPort: {{ default 9090 .Values.serviceMonitor.targetPort }}
      port: {{ default "metrics" .Values.serviceMonitor.port }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector: {{- toYaml .Values.serviceMonitor.selector | nindent 4 }}
{{- end }}