{{- if .Values.istio.enabled -}}
{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "chart.labels" .) -}}
{{- if .Values.istio.ingress }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - {{ tpl .Values.istio.ingress.host $ | quote }}
  http:
    {{- if .Values.istio.backend.api.enabled}}
    - match:
        - uri:
            prefix: {{ tpl .Values.istio.ingress.backend.api.prefix $ }}
      route:
        - destination:
            host: {{ tpl .Values.istio.ingress.backend.api.srv $ }}
            port:
              number: {{ int (tpl (.Values.istio.ingress.backend.api.port | toString) $) }}
    {{- end -}}
    - route:
        - destination:
            host: {{ tpl .Values.istio.ingress.backend.service.name $ }}
            port:
              number: {{ int (tpl (.Values.istio.ingress.backend.service.port | toString) $) }}
{{- end -}}
{{- end -}}