apiVersion: v2
name: variant-service-deployments
description: A Helm chart for Istio Objects

version: 0.1.1

kubeVersion: "^1.7.1-0"
home: https://www.drivevariant.com/
icon: https://github.com/variant-inc/in-helm-charts/raw/gh-pages/assets/variant-logo.svg
sources:
  - https://github.com/variant-inc
maintainers:
  - name: vibindaniel
    email: vibind@drivevariant.com
